import base64
import json
import struct
from pathlib import Path
from typing import Union
import plotly.graph_objects as go
import tikzplotly


def decode_bdata(obj):
    """
    Recursively decodes base64-encoded typed arrays (bdata) generated by Plotly.
    Plotly uses this format for large numpy arrays to reduce file size.
    """
    if isinstance(obj, dict) and 'bdata' in obj and 'dtype' in obj:
        try:
            bdata = base64.b64decode(obj['bdata'])
            dtype = obj['dtype']
            fmt_map = {'f4': 'f', 'f8': 'd', 'i4': 'i', 'i8': 'q', 'u4': 'I', 'u8': 'Q'}
            fmt_char = fmt_map.get(dtype, 'f')
            count = len(bdata) // struct.calcsize(fmt_char)
            return list(struct.unpack(f'<{count}{fmt_char}', bdata))
        except Exception:
            return obj
    elif isinstance(obj, dict):
        return {k: decode_bdata(v) for k, v in obj.items()}
    elif isinstance(obj, list):
        return [decode_bdata(v) for v in obj]
    return obj


def extract_plotly_fig(html_path: Union[str, Path]) -> go.Figure:
    """
    Extracts a Plotly Figure object from an HTML file containing a Plotly plot.

    :param html_path: Path to the HTML file.
    :return: go.Figure object.
    :raises ValueError: If Plotly plot structures cannot be parsed from the HTML file.
    """
    path = Path(html_path)
    if not path.is_file():
        raise FileNotFoundError(f"HTML file not found: {path}")

    with open(path, "r", encoding="utf-8") as f:
        content = f.read()

    idx = content.rfind("Plotly.newPlot(")
    if idx == -1:
        raise ValueError("Keine Plotly-Grafik im HTML gefunden (Plotly.newPlot fehlt).")

    array_start = content.find("[", idx)
    if array_start == -1:
        raise ValueError("Plotly-Datenstruktur fehlerhaft (Array-Start '[' nicht gefunden).")

    decoder = json.JSONDecoder()
    data, text_pos = decoder.raw_decode(content[array_start:])

    object_start = content.find("{", array_start + text_pos)
    if object_start == -1:
        raise ValueError("Layout-Struktur nicht gefunden (Object-Start '{' fehlt).")

    layout, _ = decoder.raw_decode(content[object_start:])

    # Decode binary typed arrays before passing to go.Figure
    data = decode_bdata(data)
    layout = decode_bdata(layout)

    # Convert layout shapes to scatter traces so tikzplotly can draw them
    if "shapes" in layout and isinstance(layout["shapes"], list):
        # We need a temporary Figure just to build the traces easily,
        # or we can directly build dict traces.
        pass

    fig = go.Figure(data=data, layout=layout)
    
    # Convert shapes (rectangles etc.) to standard scatter traces
    if hasattr(fig.layout, 'shapes') and fig.layout.shapes:
        for shape in fig.layout.shapes:
            if shape.type == 'rect':
                x0, x1 = shape.x0, shape.x1
                y0, y1 = shape.y0, shape.y1
                
                trace = go.Scatter(
                    x=[x0, x1, x1, x0, x0],
                    y=[y0, y0, y1, y1, y0],
                    mode='lines',
                    fill='toself',
                    fillcolor=shape.fillcolor,
                    line=dict(
                        color=shape.line.color if shape.line else None,
                        width=shape.line.width if shape.line else 0
                    ),
                    opacity=shape.opacity,
                    showlegend=False,
                    hoverinfo='skip'
                )
                fig.add_trace(trace)

    return fig


def convert_html_to_tikz(
    html_path: Union[str, Path],
    output_path: Union[str, Path, None] = None
) -> Path:
    """
    Converts a Plotly HTML file to a TikZ (.tex) figure file.

    :param html_path: Path to the input HTML file.
    :param output_path: Optional custom path for the output .tex file.
    :return: Path to the generated .tex file.
    """
    src_path = Path(html_path)
    if output_path:
        dest_path = Path(output_path)
    else:
        dest_path = src_path.with_suffix(".tex")

    fig = extract_plotly_fig(src_path)
    tikzplotly.save(str(dest_path), fig)

    return dest_path
